# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'RunScanWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RunScanWindow(object):
    def setupUi(self, RunScanWindow):
        RunScanWindow.setObjectName("RunScanWindow")
        RunScanWindow.resize(800, 575)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(RunScanWindow.sizePolicy().hasHeightForWidth())
        RunScanWindow.setSizePolicy(sizePolicy)
        RunScanWindow.setMinimumSize(QtCore.QSize(800, 575))
        self.centralwidget = QtWidgets.QWidget(RunScanWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout.setObjectName("verticalLayout")
        self.dataTable = QtWidgets.QTableWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dataTable.sizePolicy().hasHeightForWidth())
        self.dataTable.setSizePolicy(sizePolicy)
        self.dataTable.setMinimumSize(QtCore.QSize(575, 200))
        self.dataTable.setMouseTracking(False)
        self.dataTable.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.dataTable.setObjectName("dataTable")
        self.dataTable.setColumnCount(4)
        self.dataTable.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.dataTable.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.dataTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.dataTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.dataTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.dataTable.setHorizontalHeaderItem(3, item)
        self.verticalLayout.addWidget(self.dataTable, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.suggestionLabelVLayout = QtWidgets.QVBoxLayout()
        self.suggestionLabelVLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.suggestionLabelVLayout.setObjectName("suggestionLabelVLayout")
        self.analysisSuggestionLabe = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.analysisSuggestionLabe.sizePolicy().hasHeightForWidth())
        self.analysisSuggestionLabe.setSizePolicy(sizePolicy)
        self.analysisSuggestionLabe.setMinimumSize(QtCore.QSize(575, 200))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.analysisSuggestionLabe.setFont(font)
        self.analysisSuggestionLabe.setObjectName("analysisSuggestionLabe")
        self.suggestionLabelVLayout.addWidget(self.analysisSuggestionLabe)
        self.gridLayout.addLayout(self.suggestionLabelVLayout, 1, 0, 1, 1)
        RunScanWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(RunScanWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 37))
        self.menubar.setObjectName("menubar")
        RunScanWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(RunScanWindow)
        self.statusbar.setObjectName("statusbar")
        RunScanWindow.setStatusBar(self.statusbar)

        self.retranslateUi(RunScanWindow)
        QtCore.QMetaObject.connectSlotsByName(RunScanWindow)

    def retranslateUi(self, RunScanWindow):
        _translate = QtCore.QCoreApplication.translate
        RunScanWindow.setWindowTitle(_translate("RunScanWindow", "Run Analysis"))
        self.dataTable.setSortingEnabled(True)
        item = self.dataTable.horizontalHeaderItem(0)
        item.setText(_translate("RunScanWindow", "CVE ID"))
        item = self.dataTable.horizontalHeaderItem(1)
        item.setText(_translate("RunScanWindow", "Rate"))
        item = self.dataTable.horizontalHeaderItem(2)
        item.setText(_translate("RunScanWindow", "Engineering Hrs"))
        item = self.dataTable.horizontalHeaderItem(3)
        item.setText(_translate("RunScanWindow", "Description"))
        self.analysisSuggestionLabe.setText(_translate("RunScanWindow", "Analysis Suggestion:"))
