# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'RunScanWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RunScanWindow(object):
    def setupUi(self, RunScanWindow):
        RunScanWindow.setObjectName("RunScanWindow")
        RunScanWindow.resize(800, 575)
        RunScanWindow.setMinimumSize(QtCore.QSize(800, 575))
        RunScanWindow.setMaximumSize(QtCore.QSize(800, 575))
        self.centralwidget = QtWidgets.QWidget(RunScanWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 771, 391))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.testTable = QtWidgets.QTableWidget(self.verticalLayoutWidget)
        self.testTable.setObjectName("testTable")
        self.testTable.setColumnCount(4)
        self.testTable.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.testTable.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.testTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.testTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.testTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.testTable.setHorizontalHeaderItem(3, item)
        self.verticalLayout.addWidget(self.testTable)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 410, 241, 31))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.suggestionLabelVLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.suggestionLabelVLayout.setContentsMargins(0, 0, 0, 0)
        self.suggestionLabelVLayout.setObjectName("suggestionLabelVLayout")
        self.analysisSuggestionLabe = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.analysisSuggestionLabe.setFont(font)
        self.analysisSuggestionLabe.setObjectName("analysisSuggestionLabe")
        self.suggestionLabelVLayout.addWidget(self.analysisSuggestionLabe)
        RunScanWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(RunScanWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        RunScanWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(RunScanWindow)
        self.statusbar.setObjectName("statusbar")
        RunScanWindow.setStatusBar(self.statusbar)

        self.retranslateUi(RunScanWindow)
        QtCore.QMetaObject.connectSlotsByName(RunScanWindow)

    def retranslateUi(self, RunScanWindow):
        _translate = QtCore.QCoreApplication.translate
        RunScanWindow.setWindowTitle(_translate("RunScanWindow", "Run Analysis"))
        item = self.testTable.verticalHeaderItem(0)
        item.setText(_translate("RunScanWindow", "Vulnerability Match"))
        item = self.testTable.horizontalHeaderItem(0)
        item.setText(_translate("RunScanWindow", "CVE ID"))
        item = self.testTable.horizontalHeaderItem(1)
        item.setText(_translate("RunScanWindow", "Cost"))
        item = self.testTable.horizontalHeaderItem(2)
        item.setText(_translate("RunScanWindow", "Engineering Hrs"))
        item = self.testTable.horizontalHeaderItem(3)
        item.setText(_translate("RunScanWindow", "Description"))
        self.analysisSuggestionLabe.setText(_translate("RunScanWindow", "Analysis Suggestion:"))
