# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'RunScanWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RunScanWindow(object):
    def setupUi(self, RunScanWindow):
        RunScanWindow.setObjectName("RunScanWindow")
        RunScanWindow.resize(800, 575)
        RunScanWindow.setMinimumSize(QtCore.QSize(800, 575))
        RunScanWindow.setMaximumSize(QtCore.QSize(800, 575))
        self.centralwidget = QtWidgets.QWidget(RunScanWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 781, 511))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.elementLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.elementLayout.setContentsMargins(0, 0, 0, 0)
        self.elementLayout.setObjectName("elementLayout")
        self.elementLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.elementLabel.setText("")
        self.elementLabel.setObjectName("elementLabel")
        self.elementLayout.addWidget(self.elementLabel)
        RunScanWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(RunScanWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        RunScanWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(RunScanWindow)
        self.statusbar.setObjectName("statusbar")
        RunScanWindow.setStatusBar(self.statusbar)

        self.retranslateUi(RunScanWindow)
        QtCore.QMetaObject.connectSlotsByName(RunScanWindow)

    def retranslateUi(self, RunScanWindow):
        _translate = QtCore.QCoreApplication.translate
        RunScanWindow.setWindowTitle(_translate("RunScanWindow", "Run Analysis"))
